---
# handlers file for common_role

#- name: Restart service Telegraf
#  systemd:
#    name: telegraf
#    state: restarted
#    daemon_reload: yes
#    enabled: yes
#    force: yes
#
- name: Restart Service SSH
  systemd:
    name: sshd
    state: restarted
    force: yes
