version: 2.1

jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            echo "Number of shell scripts found: $(find . -type f -name '*.sh' | wc -l)"
            find . -type f -name '*.sh' -exec shellcheck --external-sources {} +

  yamllint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install YamlLint
          command: pip install yamllint
      - run:
          name: Run YamlLint
          command: |
            wget -q https://gist.githubusercontent.com/procamora/a8e68a2067003994581562e35e364ade/raw/87940e46599fc8f680e4b42f6ddbca0dddad0802/my_relased.yml -O .yamllint.yml
            yamllint -c .yamllint.yml . | tee ./output
            if grep -q "error" ./output; then
              echo "Errors detected"
              cat ./output
              exit 1
            fi


workflows:
  version: 2
  parallelism: 4
  check-build:
    jobs:
      - shellcheck:
          filters:
            branches:
              only:
                - main
                - master
                - dev
      - yamllint:
          filters:
            branches:
              only:
                - main
                - master
                - dev