---

# https://docs.ansible.com/ansible/latest/collections/community/general/archive_module.html
- name: Create a tar.gz archive of a single file.
  community.general.archive:
    path: "{{ playbook_dir }}/../"
    dest: /tmp/irrigation.tar.gz
    format: gz
    force_archive: true
  delegate_to: localhost

- name: Create directory irrigation_controller
  file:
    path: "/home/{{ procamora_user }}/irrigation_controller/"
    state: directory


- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: /tmp/irrigation.tar.gz
    dest: "/home/{{ procamora_user }}/irrigation_controller/"
    remote_src: no
    owner: "{{ procamora_user }}"

- name: Detete /tmp/irrigation.tar.gz
  file:
    path: /tmp/irrigation.tar.gz
    state: absent
  delegate_to: localhost

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: "/home/{{ procamora_user }}/irrigation_controller/requirements.txt"