---
# tasks file for common_role

# todo ok
- name: Main | pre_tasks
  include_tasks: pre_tasks.yml

## todo ok
- name: Main | raspi_config
  include_tasks: raspi_config.yml

## todo ok
- name: Main | reboot
  include_tasks: reboot.yml

# todo ok
- name: Main | Install packages
  include_tasks: packages.yml

- name: Main | reboot
  include_tasks: reboot.yml

#- name: Main | Install Filebeat
#  include_tasks: filebeat.yml

- name: Main | Configure firewalld
  include_tasks: firewalld.yml

- name: Main | user
  include_tasks: user.yml

# todo ok
#- name: Main | Install motd
#  include_tasks: motd.yml

#- name: Main | Install custom_workspace
#  include_tasks: zsh.yml


#- name: Copy Complete directory
#  copy:
#    src: "{{ playbook_dir }}/../"
#    dest: "/home/{{ procamora_user }}/test/"
#    remote_src: no
#    directory_mode: yes

- name: Main | irrigation
  include_tasks: irrigation.yml

#
#- name: Post Tasks | Force Reboot if change main user
#  reboot:
#    msg: "Reboot initiated by Ansible for kernel updates"
#    connect_timeout: 5
#    reboot_timeout: 300
#    pre_reboot_delay: 0
#    post_reboot_delay: 30
#    test_command: uptime
#  when: _create_user.changed
