---
# tasks file for common_role

# todo ok
- name: Main | pre_tasks
  include_tasks: pre_tasks.yml

## todo ok
- name: Main | raspi_config
  include_tasks: raspi_config.yml

## todo ok
- name: Main | reboot
  include_tasks: reboot.yml

# todo ok
- name: Main | Install packages
  include_tasks: packages.yml

- name: Main | reboot
  include_tasks: reboot.yml

#- name: Main | Install Filebeat
#  include: filebeat.yml

#- name: Main | Configure firewalld
#  include: firewalld.yml
#  when:
#    - ansible_os_family == 'RedHat'

- name: Main | user
  include_tasks: user.yml

# todo ok
- name: Main | Install motd
  include_tasks: motd.yml

#- name: Main | Install custom_workspace
#  include: zsh.yml


#- name: Copy Complete directory
#  copy:
#    src: "{{ playbook_dir }}/../"
#    dest: "/home/{{ procamora_user }}/test/"
#    remote_src: no
#    directory_mode: yes

# https://docs.ansible.com/ansible/latest/collections/community/general/archive_module.html
- name: Create a tar.gz archive of a single file.
  community.general.archive:
    path: "{{ playbook_dir }}/../"
    dest: /tmp/irrigation.tar.gz
    format: gz
    force_archive: true


- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: /tmp/irrigation.tar.gz
    dest: "/home/{{ procamora_user }}/irrigation_controller/"
#    remote_src: yes
    owner: "{{ procamora_user }}"

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: "/home/{{ procamora_user }}/test/requirements.txt"