---

- block:
    - name: Packages | Update repository with apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Packages | Upgrade all packages with apt
      apt:
        name: "*"
        state: latest

    - name: Packages | Install packages with apt
      apt:
        name:
          - netcat
          - vim
          - wget
          - curl
          - git
          - apt-transport-https
          - python3
          - python3-dev
          - python3-pip
          - python3-passlib
          - zsh
          - selinux-policy-dev
          - gpg
          - trash-cli
          - tree
          - sudo
          - tmux
          - raspberrypi-kernel
          - raspberrypi-kernel-headers
          - atop
        # - auditd
        # - ntp
        state: latest
        update_cache: yes
        cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: "/home/{{ procamora_user }}/test/requirements.txt"