---

- name: Users | Create main group
  group:
    name: "{{ procamora_user }}"
    state: present

# group gpio for non use root to access a gpio (need reboot for apply change)
- name: Users | Create main user
  user:
    name: "{{ procamora_user }}"
    password: "{{ procamora_pass | password_hash('sha512') }}"
    shell: /bin/bash
    groups: adm, dialout, sudo, plugdev, gpio
    group: "{{ procamora_user }}"
    append: yes
    force: yes
    comment: "Default user"
    ssh_key_file:
  register: _create_user


- name: Irrigation | Create ~/.ssh
  ansible.builtin.file:
    path: "/home/{{ procamora_user }}/.ssh/"
    state: directory
    mode: '0700'
    owner: "{{ procamora_user }}"
    group: "{{ procamora_user }}"

- name: Users | Copy public key in ~/.ssh
  copy:
    src: ~/.ssh/services.pub
    dest: "/home/{{ procamora_user }}/.ssh/authorized_keys"
    mode: 0600
    owner: "{{ procamora_user }}"
    group: "{{ procamora_user }}"
    remote_src: no

#- name: Main | Set user in sudoers
#  lineinfile:
#    path: "/etc/sudoers.d/{{ procamora_user }}"
#    state: present
#    regexp: '^{{ procamora_user }}'
#    line: '{{ procamora_user }} ALL=(ALL) NOPASSWD: ALL'
#    backrefs: no
#    create: yes
#    validate: 'visudo -cf %s'

- name: Users | Copy {{ procamora_user }} in sudoers.d/
  template:
    src: procamora.sudoers.j2
    dest: "/etc/sudoers.d/{{ procamora_user }}"
    mode: 0660
    validate: 'visudo -cf %s'

- name: Users | Disable login user pi
  ansible.builtin.user:
    name: "pi"
    state: present
    password_lock: true
    shell: "/sbin/nologin"

- name: Users | Configure sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regex }}'
    line: '{{ item.line }}'
    backrefs: yes
  loop:
    - { regex: '^( )*#?( )*PubkeyAuthentication( )*.*$', line: "PubkeyAuthentication yes" }
    - { regex: '^( )*#?( )*PasswordAuthentication( )*.*$', line: "PasswordAuthentication no" }
  notify: Restart Service SSH
