---

- name: Users | Create main group
  group:
    name: "{{ procamora_user }}"
    state: present

# group gpio for non use root to access a gpio (need reboot for apply change)
- name: Users | Create main user
  user:
    name: "{{ procamora_user }}"
    password: "{{ procamora_pass | password_hash('sha512') }}"
    shell: /bin/bash
    groups: adm, dialout, sudo, plugdev, gpio
    group: "{{ procamora_user }}"
    append: yes
    force: yes
    comment: "Default user"
  register: _create_user

#- name: Main | Set user in sudoers
#  lineinfile:
#    path: "/etc/sudoers.d/{{ procamora_user }}"
#    state: present
#    regexp: '^{{ procamora_user }}'
#    line: '{{ procamora_user }} ALL=(ALL) NOPASSWD: ALL'
#    backrefs: no
#    create: yes
#    validate: 'visudo -cf %s'

- name: Users | Copy {{ procamora_user }} in sudoers.d/
  template:
    src: procamora.sudoers.j2
    dest: "/etc/sudoers.d/{{ procamora_user }}"
    mode: 0660
    validate: 'visudo -cf %s'

# TODO DISABLE USER PI


